# Generated by Django 5.0.6 on 2024-07-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MH', 'Mental Health'), ('HD', 'Heart Disease'), ('CV', 'Covid19'), ('IM', 'Immunization')], max_length=100),
        ),
    ]
